INSERT INTO `paneltech`.`full_field_products002`
(
    `uri`,
    `site`,
    `product_title`,
    `product_name`,
    `big_img_url`,
    `img_urls`,
    `category_path`,
    `brand`,
    `model`,
    `model_raw_text`,
    `specification`,
    `material`,
    `price`,
    `price_raw_text`,
    `min_amount_to_buy`,
    `max_amount_to_buy`,
    `sales_volume`,
    `stock_prompt`,
    `inventory_amount`,
    `favorable_rate`,
    `good_reviews_raw_text`,
    `good_reviews`,
    `normal_reviews_raw_text`,
    `normal_reviews`,
    `bad_reviews_raw_text`,
    `bad_reviews`,
    `shop_name`,
    `shop_url`,
    `shop_location`,
    `shop_tel`,
    `shop_scores`,
    `shop_stars`,
    `delivery_from`,
    `express_fee`,
    `express_fee_raw_text`,
    `comment_count`,
    `comment_count_raw_text`,
    `coupon`,
    `coupon_comment`,
    `promotion`,
    `delivery_by`,
    `summary_service`,
    `services`,
    `variants`,
    `base_uri`
    )
VALUES
    (
        <{uri: }>,
        <{site: }>,
        <{product_title: }>,
        <{product_name: }>,
        <{big_img_url: }>,
        <{img_urls: }>,
        <{category_path: }>,
        <{brand: }>,
        <{model: }>,
        <{model_raw_text: }>,
        <{specification: }>,
        <{material: }>,
        <{price: }>,
        <{price_raw_text: }>,
        <{min_amount_to_buy: }>,
        <{max_amount_to_buy: }>,
        <{sales_volume: }>,
        <{stock_prompt: }>,
        <{inventory_amount: }>,
        <{favorable_rate: }>,
        <{good_reviews_raw_text: }>,
        <{good_reviews: }>,
        <{normal_reviews_raw_text: }>,
        <{normal_reviews: }>,
        <{bad_reviews_raw_text: }>,
        <{bad_reviews: }>,
        <{shop_name: }>,
        <{shop_url: }>,
        <{shop_location: }>,
        <{shop_tel: }>,
        <{shop_scores: }>,
        <{shop_stars: }>,
        <{delivery_from: }>,
        <{express_fee: }>,
        <{express_fee_raw_text: }>,
        <{comment_count: }>,
        <{comment_count_raw_text: }>,
        <{coupon: }>,
        <{coupon_comment: }>,
        <{promotion: }>,
        <{delivery_by: }>,
        <{summary_service: }>,
        <{services: }>,
        <{variants: }>,
        <{base_uri: }>
     );
