INSERT INTO `paneltech`.`integrated_products002`
(
 `site`,
 `big_img_url`,
 `product_name`,
 `brand`,
 `model`,
 `specification`,
 `material`,
 `price`,
 `min_amount_to_buy`,
 `max_amount_to_buy`,
 `inventory_amount`,
 `stock_prompt`,
 `sales_volume`,
 `favorable_rate`,
 `good_reviews`,
 `normal_reviews`,
 `bad_reviews`,
 `shop_name`,
 `shop_url`,
 `shop_location`,
 `shop_tel`,
 `shop_scores`,
 `express_fee`
 )
VALUES
    (
        <{site: }>,
        <{big_img_url: }>,
        <{product_name: }>,
        <{brand: }>,
        <{model: }>,
        <{specification: }>,
        <{material: }>,
        <{price: }>,
        <{min_amount_to_buy: }>,
        <{max_amount_to_buy: }>,
        <{inventory_amount: }>,
        <{stock_prompt: }>,
        <{sales_volume: }>,
        <{favorable_rate: }>,
        <{good_reviews: }>,
        <{normal_reviews: }>,
        <{bad_reviews: }>,
        <{shop_name: }>,
        <{shop_url: }>,
        <{shop_location: }>,
        <{shop_tel: }>,
        <{shop_scores: }>,
        <{express_fee: }>
     );
