services:
  mongodb:
    image: 'mongo:latest'
    container_name: 'mongodb'
    restart: always
    ports:
      - '27017:27017'
    command: ["--bind_ip_all"]
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

  proxy-hub:
    image: 'proxy-hub:latest'
    container_name: 'proxy-hub'
    ports:
      - '8192:8192'
    profiles: ["proxy"]  # ✅ Only start when profile=proxy, e.g., docker compose --profile proxy up

  pulsar-rpa:
    image: 'pulsar-rpa:latest'
    container_name: 'pulsar-rpa'
    depends_on:
      - 'mongodb'
    environment:
      "gora.mongodb.servers": mongodb:27017
      "spring.data.mongodb.uri": mongodb://mongodb:27017/pulsar-rpa
      BROWSER_DISPLAY_MODE: HEADLESS
      SERVER_PORT: 8182
      SERVER_ADDRESS: 0.0.0.0
    ports:
      - '8182:8182'
    networks:
      - backend
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8182/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  backend:
    driver: bridge

volumes:
  mongodb_data:
