name: Docker Build
description: Build Docker images with multi-platform support and optimization
author: platonai
branding:
  icon: 'box'
  color: 'blue'

inputs:
  image_name:
    description: 'Docker image name (required)'
    required: true
  version:
    description: 'Image version/tag (required)'
    required: true
  dockerfile:
    description: 'Dockerfile path (default: Dockerfile)'
    required: false
    default: 'Dockerfile'
  build_context:
    description: 'Build context path (default: .)'
    required: false
    default: '.'
  timeout_minutes:
    description: 'Build timeout in minutes (default: 15)'
    required: false
    default: '15'
  platforms:
    description: 'Target platforms (default: linux/amd64)'
    required: false
    default: 'linux/amd64'
  build_args:
    description: 'Build arguments (key=value, one per line)'
    required: false
    default: ''
  cache_from:
    description: 'Cache source images'
    required: false
    default: ''
  push_image:
    description: 'Push image after build (default: false)'
    required: false
    default: 'false'

outputs:
  image_id:
    description: 'Built image ID'
    value: ${{ steps.build.outputs.image_id }}
  image_digest:
    description: 'Image digest'
    value: ${{ steps.build.outputs.digest }}
  image_size:
    description: 'Image size in bytes'
    value: ${{ steps.image-info.outputs.size }}

runs:
  using: "composite"
  steps:
    - name: Validate Build Context
      shell: bash
      run: |
        echo "::group::Build Context Validation"
        
        if [ ! -f "${{ inputs.dockerfile }}" ]; then
          echo "❌ Dockerfile not found: ${{ inputs.dockerfile }}"
          exit 1
        fi
        
        if [ ! -d "${{ inputs.build_context }}" ]; then
          echo "❌ Build context directory not found: ${{ inputs.build_context }}"
          exit 1
        fi
        
        echo "✅ Dockerfile found: ${{ inputs.dockerfile }}"
        echo "✅ Build context: ${{ inputs.build_context }}"
        
        # Show Dockerfile content summary
        echo ""
        echo "📋 Dockerfile summary:"
        echo "  - Size: $(wc -l < ${{ inputs.dockerfile }}) lines"
        echo "  - Base image: $(grep -m1 '^FROM' ${{ inputs.dockerfile }} | cut -d' ' -f2 || echo 'unknown')"
        
        # Check for multi-stage builds
        stage_count=$(grep -c '^FROM' ${{ inputs.dockerfile }} || echo "1")
        if [ $stage_count -gt 1 ]; then
          echo "  - Multi-stage build: $stage_count stages"
        fi
        
        echo "::endgroup::"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: ${{ inputs.platforms }}

    - name: Prepare Build Arguments
      shell: bash
      run: |
        echo "::group::Build Preparation"
        
        # Process build arguments
        if [ -n "${{ inputs.build_args }}" ]; then
          echo "📋 Build arguments:"
          echo "${{ inputs.build_args }}" | while IFS= read -r arg; do
            if [ -n "$arg" ]; then
              echo "  - $arg"
            fi
          done
        fi
        
        # Prepare tags
        TAGS="${{ inputs.image_name }}:${{ inputs.version }}"
        
        # Add latest tag if version is not a snapshot or pre-release
        if [[ "${{ inputs.version }}" != *"SNAPSHOT"* ]] && [[ "${{ inputs.version }}" != *"-"* ]]; then
          TAGS="$TAGS,${{ inputs.image_name }}:latest"
        fi
        
        echo "DOCKER_TAGS=$TAGS" >> $GITHUB_ENV
        
        echo "📋 Tags to be created:"
        echo "$TAGS" | tr ',' '\n' | sed 's/^/  - /'
        
        echo "::endgroup::"

    - name: Build Docker Image
      id: build
      shell: bash
      run: |
        echo "::group::Docker Build"
        
        start_time=$(date +%s)
        
        echo "🐳 Building Docker image..."
        echo "📋 Build Configuration:"
        echo "  - Image: ${{ inputs.image_name }}"
        echo "  - Version: ${{ inputs.version }}"
        echo "  - Dockerfile: ${{ inputs.dockerfile }}"
        echo "  - Context: ${{ inputs.build_context }}"
        echo "  - Platforms: ${{ inputs.platforms }}"
        echo "  - Timeout: ${{ inputs.timeout_minutes }} minutes"
        
        # Build docker command
        build_cmd="docker buildx build"
        build_cmd="$build_cmd --file ${{ inputs.dockerfile }}"
        build_cmd="$build_cmd --platform ${{ inputs.platforms }}"
        
        # Add tags
        for tag in $(echo "$DOCKER_TAGS" | tr ',' ' '); do
          build_cmd="$build_cmd --tag $tag"
        done
        
        # Add build arguments
        if [ -n "${{ inputs.build_args }}" ]; then
          echo "${{ inputs.build_args }}" | while IFS= read -r arg; do
            if [ -n "$arg" ]; then
              build_cmd="$build_cmd --build-arg $arg"
            fi
          done
        fi
        
        # Add cache configuration
        if [ -n "${{ inputs.cache_from }}" ]; then
          build_cmd="$build_cmd --cache-from ${{ inputs.cache_from }}"
        fi
        
        # Add push option
        if [ "${{ inputs.push_image }}" == "true" ]; then
          build_cmd="$build_cmd --push"
        else
          build_cmd="$build_cmd --load"
        fi
        
        # Add build context
        build_cmd="$build_cmd ${{ inputs.build_context }}"
        
        echo "🚀 Executing: $build_cmd"
        echo ""
        
        # Execute with timeout
        timeout_seconds=$(( ${{ fromJSON(inputs.timeout_minutes) }} * 60 ))
        
        if timeout $timeout_seconds $build_cmd; then
          end_time=$(date +%s)
          build_time=$((end_time - start_time))
          echo ""
          echo "✅ Docker image built successfully in ${build_time} seconds"
          
          # Get image ID (only works if not pushing)
          if [ "${{ inputs.push_image }}" != "true" ]; then
            image_id=$(docker images --format "{{.ID}}" "${{ inputs.image_name }}:${{ inputs.version }}" | head -1)
            echo "image_id=$image_id" >> $GITHUB_OUTPUT
          fi
          
        else
          end_time=$(date +%s)
          build_time=$((end_time - start_time))
          echo ""
          echo "❌ Docker build failed or timed out after ${build_time} seconds"
          exit 1
        fi
        
        echo "::endgroup::"

    - name: Image Information
      id: image-info
      if: success() && inputs.push_image != 'true'
      shell: bash
      run: |
        echo "::group::Image Information"
        
        echo "📊 Built images:"
        docker images --format "table {{.Repository}}:{{.Tag}}\t{{.Size}}\t{{.CreatedAt}}" | \
          grep "${{ inputs.image_name }}" || true
        
        # Get detailed image information
        image_name="${{ inputs.image_name }}:${{ inputs.version }}"
        
        if docker image inspect "$image_name" > /dev/null 2>&1; then
          # Get image size
          size=$(docker image inspect "$image_name" --format '{{.Size}}')
          size_mb=$((size / 1024 / 1024))
          
          echo "size=$size" >> $GITHUB_OUTPUT
          
          echo ""
          echo "📋 Image Details:"
          echo "  - Name: $image_name"
          echo "  - Size: ${size_mb} MB"
          echo "  - Architecture: $(docker image inspect "$image_name" --format '{{.Architecture}}')"
          echo "  - OS: $(docker image inspect "$image_name" --format '{{.Os}}')"
          
          # Show layers
          echo ""
          echo "📦 Image layers:"
          docker history "$image_name" --format "table {{.CreatedBy}}\t{{.Size}}" | head -10
          
          # Security scan (if available)
          if command -v docker scout &> /dev/null; then
            echo ""
            echo "🔍 Security scan:"
            docker scout quickview "$image_name" 2>/dev/null || echo "Security scan not available"
          fi
        fi
        
        echo "::endgroup::"

    - name: Test Image
      if: success() && inputs.push_image != 'true'
      shell: bash
      run: |
        echo "::group::Image Test"
        
        image_name="${{ inputs.image_name }}:${{ inputs.version }}"
        
        echo "🧪 Testing image startup..."
        
        # Basic smoke test - try to run the image briefly
        if timeout 30 docker run --rm "$image_name" --help > /dev/null 2>&1; then
          echo "✅ Image help command successful"
        elif timeout 30 docker run --rm "$image_name" --version > /dev/null 2>&1; then
          echo "✅ Image version command successful"
        else
          echo "⚠️ Basic image tests inconclusive (this may be normal for web applications)"
        fi
        
        echo "::endgroup::"