drop table if exists `paneltech`.`full_field_products002`;

CREATE TABLE `full_field_products002` (
   `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
   `uri` varchar(1024) DEFAULT NULL,
   `site` varchar(16) DEFAULT NULL,
   `product_title` varchar(1024) DEFAULT NULL,
   `product_name` varchar(255) DEFAULT NULL,
   `big_img_url` varchar(1024) DEFAULT NULL,
   `img_urls` text,
   `category_path` varchar(255) DEFAULT NULL,
   `brand` varchar(64) DEFAULT NULL,
   `model` varchar(64) DEFAULT NULL,
   `model_raw_text` varchar(1024) DEFAULT NULL,
   `specification` varchar(255) DEFAULT NULL,
   `material` varchar(255) DEFAULT NULL,
   `price` varchar(64) DEFAULT NULL,
   `price_raw_text` varchar(255) DEFAULT NULL,
   `min_amount_to_buy` varchar(8) DEFAULT NULL,
   `max_amount_to_buy` varchar(8) DEFAULT NULL,
   `sales_volume` varchar(8) DEFAULT NULL,
   `stock_prompt` varchar(32) DEFAULT NULL,
   `inventory_amount` varchar(8) DEFAULT NULL,
   `favorable_rate` varchar(8) DEFAULT NULL,
   `good_reviews_raw_text` varchar(16) DEFAULT NULL,
   `good_reviews` varchar(16) DEFAULT NULL,
   `normal_reviews_raw_text` varchar(16) DEFAULT NULL,
   `normal_reviews` varchar(16) DEFAULT NULL,
   `bad_reviews_raw_text` varchar(16) DEFAULT NULL,
   `bad_reviews` varchar(16) DEFAULT NULL,
   `shop_name` varchar(64) DEFAULT NULL,
   `shop_url` varchar(1024) DEFAULT NULL,
   `shop_location` varchar(255) DEFAULT NULL,
   `shop_tel` varchar(8) DEFAULT NULL,
   `shop_scores` text,
   `shop_stars` varchar(32) DEFAULT NULL,
   `delivery_from` varchar(8) DEFAULT NULL,
   `express_fee` varchar(8) DEFAULT NULL,
   `express_fee_raw_text` varchar(32) DEFAULT NULL,
   `comment_count` varchar(8) DEFAULT NULL,
   `comment_count_raw_text` varchar(32) DEFAULT NULL,
   `coupon` varchar(64) DEFAULT NULL,
   `coupon_comment` varchar(64) DEFAULT NULL,
   `promotion` text,
   `delivery_by` varchar(128) DEFAULT NULL,
   `summary_service` text,
   `services` text,
   `variants` text,
   `base_uri` text,
   `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='auto created table from x-sql';
