name: CI

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '.github/**'
      - 'bin/**'
      - 'docs/**'
      - 'docker/**'
      - '**.md'
  # Allow manual workflow runs
  workflow_dispatch:

env:
  IMAGE_NAME: galaxyeye88/pulsar-rpa-pro

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Common Workflow Steps - Build and Test
        uses: ./.github/actions/build-test
        with:
          image_name: galaxyeye88/pulsar-rpa-pro
          version: ${{ env.VERSION }}
          deepseek_api_key: ${{ secrets.DEEPSEEK_API_KEY }}
          proxy_rotation_url: ${{ secrets.PROXY_ROTATION_URL }}
