name: CI

on:
  push:
    branches:
      - main-disabled
      - master-disabled
  # Allow manual workflow runs
  workflow_dispatch:

env:
  IMAGE_NAME: galaxyeye88/pulsar-rpa-pro

jobs:
  build-test-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Configure Maven settings.xml if missing
        run: |
          mkdir -p ~/.m2
          cp docs/development/maven/settings.xml ~/.m2/settings.xml

      - name: Read VERSION
        id: version
        run: |
          echo "VERSION=$(head -n 1 VERSION)" >> $GITHUB_ENV

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Maven build and deploy to local repo
        run: |
          chmod +x ./mvnw
          ./mvnw clean install -DskipTests -Pall-modules

      - name: Run Tests
        run: ./mvnw test -Pall-modules

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$VERSION -t $IMAGE_NAME:latest -f Dockerfile .

      - name: Start Docker container
        run: |
          docker run -d --rm --name pulsar-rpa-pro-test -p 8182:8182 $IMAGE_NAME:$VERSION
          sleep 10  # Wait for Spring Boot to start

      - name: Run curl integration tests
        run: |
          find bin/ -name "*.sh" -exec chmod +x {} \;
          ./bin/run-integration-test.sh || (echo "Integration test failed" && exit 1)

      - name: Stop Docker container
        if: always()
        run: docker stop pulsar-rpa-pro-test || true
