name: CI

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - 'bin/**'
      - 'docs/**'
      - 'docker/**'
      - '**.md'
  # Allow manual workflow runs
  workflow_dispatch:

env:
  IMAGE_NAME: galaxyeye88/pulsar-rpa-pro

jobs:
  build-test-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Read VERSION
        id: version
        run: |
          echo "VERSION=$(head -n 1 VERSION)" >> $GITHUB_ENV

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2




      - name: Start MongoDB container
        run: |
          docker compose up mongodb -d
          sleep 5 # Wait for MongoDB to start

      - name: Check MongoDB container status
        run: |
          if [ "$(docker inspect -f '{{.State.Running}}' mongodb)" != "true" ]; then
            echo "MongoDB container is not running!" && exit 1
          fi


      - name: Maven build and deploy to local repo
        run: |
          chmod +x ./mvnw
          ./mvnw clean install -DskipTests -Pall-modules

      - name: Run Tests
        run: ./mvnw test -Pall-modules

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$VERSION -t $IMAGE_NAME:latest -f Dockerfile .

      - name: Start Docker container
        run: |
          # Start container
          docker run -d --rm --name pulsar-rpa-test -p 8182:8182 -e DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY} $IMAGE_NAME:$VERSION
          # docker run -d -p 8182:8182 -e DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY} $IMAGE_NAME:$VERSION
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}

      - name: Wait for Service Available
        run: |
          # Wait for the service to be available
          for i in {1..30}; do
            if curl -s http://localhost:8182/actuator/health | grep '"status":"UP"'; then
              echo "Service is up!"
              break
            fi
            echo "Waiting for service to be available..."
            sleep 2
          done

      - name: Run curl integration tests
        run: |
          # Run integration tests
          find bin/ -name "*.sh" -exec chmod +x {} \;

          if ! ./bin/run-integration-test.sh; then
            echo "Integration test failed"
            docker logs pulsar-rpa-test
            docker stop pulsar-rpa-test || true
            exit 1
          fi

      - name: Stop Docker container
        if: always()
        run: docker stop pulsar-rpa-test || true



      - name: Stop MongoDB container
        if: always()
        run: |
          docker compose down || true
