name: Code Quality

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main ]
  # Allow manual workflow runs
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Configure Maven settings.xml if missing
        run: |
          mkdir -p ~/.m2
          cp docs/development/maven/settings.xml ~/.m2/settings.xml
          cat ~/.m2/settings.xml
          echo "Checking if scent-bom can be downloaded..."
          cd /tmp
          if ! curl --fail --silent --show-error https://static.platonai.cn/repo/ai/platon/scent/scent-bom/3.0.3/scent-bom-3.0.3.pom; then
            echo "Failed to download scent-bom-3.0.3.pom" && exit 1
          fi
          cd -

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Initialize CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java, kotlin

      # Compile the codebase to allow CodeQL to perform analysis
      - name: Build with Maven
        run: ./mvnw install -DskipTests -Pall-modules

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:java"

  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Checkstyle
        uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning 