name: Nightly Build

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  # Allow manual workflow runs
  workflow_dispatch:

jobs:
  nightly-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Common Workflow Steps - Build and Test
        uses: ./.github/actions/build-test
        with:
          image_name: galaxyeye88/pulsar-rpa-pro
          version: ${{ env.VERSION }}
          deepseek_api_key: ${{ secrets.DEEPSEEK_API_KEY }}
          proxy_rotation_url: ${{ secrets.PROXY_ROTATION_URL }}
